CREATE SCHEMA stripe;
CREATE TABLE stripe.application (
  "id" text not null,
  "name" text,
  "object" text not null
);
CREATE TABLE stripe.account (
  "business_profile" jsonb not null,
  "business_type" text,
  "capabilities" jsonb not null,
  "charges_enabled" boolean not null,
  "company" jsonb not null,
  "controller" jsonb not null,
  "country" text not null,
  "created" integer not null,
  "default_currency" text not null,
  "details_submitted" boolean not null,
  "email" text,
  "external_accounts" jsonb not null,
  "future_requirements" jsonb not null,
  "id" text not null,
  "individual" jsonb not null,
  "metadata" jsonb not null,
  "object" text not null,
  "payouts_enabled" boolean not null,
  "requirements" jsonb not null,
  "settings" jsonb not null,
  "tos_acceptance" jsonb not null,
  "type" text not null
);
CREATE TABLE stripe.application_fee (
  "account" jsonb not null,
  "amount" integer not null,
  "amount_refunded" integer not null,
  "application" jsonb not null,
  "balance_transaction" jsonb not null,
  "charge" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "originating_transaction" jsonb not null,
  "refunded" boolean not null,
  "refunds" jsonb not null
);
CREATE TABLE stripe.refund (
  "amount" integer not null,
  "balance_transaction" jsonb not null,
  "charge" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "description" text not null,
  "failure_balance_transaction" jsonb not null,
  "failure_reason" text not null,
  "id" text not null,
  "instructions_email" text not null,
  "metadata" jsonb,
  "next_action" jsonb not null,
  "object" text not null,
  "payment_intent" jsonb not null,
  "reason" text,
  "receipt_number" text,
  "source_transfer_reversal" jsonb not null,
  "status" text,
  "transfer_reversal" jsonb not null
);
CREATE TABLE stripe.balance (
  "available" jsonb not null,
  "connect_reserved" jsonb not null,
  "instant_available" jsonb not null,
  "issuing" jsonb not null,
  "livemode" boolean not null,
  "object" text not null,
  "pending" jsonb not null
);
CREATE TABLE stripe.configuration (
  "active" boolean not null,
  "application" jsonb not null,
  "business_profile" jsonb not null,
  "created" integer not null,
  "default_return_url" text,
  "features" jsonb not null,
  "id" text not null,
  "is_default" boolean not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "updated" integer not null
);
CREATE TABLE stripe.session (
  "configuration" jsonb not null,
  "created" integer not null,
  "customer" text not null,
  "id" text not null,
  "livemode" boolean not null,
  "locale" text,
  "object" text not null,
  "on_behalf_of" text,
  "return_url" text,
  "url" text not null
);
CREATE TABLE stripe.capability (
  "account" jsonb not null,
  "future_requirements" jsonb not null,
  "id" text not null,
  "object" text not null,
  "requested" boolean not null,
  "requested_at" integer,
  "requirements" jsonb not null,
  "status" text not null
);
CREATE TABLE stripe.cash_balance (
  "available" jsonb,
  "customer" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "settings" jsonb not null
);
CREATE TABLE stripe.charge (
  "amount" integer not null,
  "amount_captured" integer not null,
  "amount_refunded" integer not null,
  "application" jsonb not null,
  "application_fee" jsonb not null,
  "application_fee_amount" integer,
  "balance_transaction" jsonb not null,
  "billing_details" jsonb not null,
  "calculated_statement_descriptor" text,
  "captured" boolean not null,
  "created" integer not null,
  "currency" text not null,
  "customer" jsonb not null,
  "description" text,
  "disputed" boolean not null,
  "failure_balance_transaction" jsonb not null,
  "failure_code" text,
  "failure_message" text,
  "fraud_details" jsonb not null,
  "id" text not null,
  "invoice" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "outcome" jsonb not null,
  "paid" boolean not null,
  "payment_intent" jsonb not null,
  "payment_method" text,
  "payment_method_details" jsonb not null,
  "radar_options" jsonb not null,
  "receipt_email" text,
  "receipt_number" text,
  "receipt_url" text,
  "refunded" boolean not null,
  "refunds" jsonb not null,
  "review" jsonb not null,
  "shipping" jsonb not null,
  "source_transfer" jsonb not null,
  "statement_descriptor" text,
  "statement_descriptor_suffix" text,
  "status" text not null,
  "transfer" jsonb not null,
  "transfer_data" jsonb not null,
  "transfer_group" text
);
CREATE TABLE stripe.dispute (
  "amount" integer not null,
  "balance_transactions" jsonb not null,
  "charge" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "evidence" jsonb not null,
  "evidence_details" jsonb not null,
  "id" text not null,
  "is_charge_refundable" boolean not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "payment_intent" jsonb not null,
  "reason" text not null,
  "status" text not null
);
CREATE TABLE stripe.coupon (
  "amount_off" integer,
  "applies_to" jsonb not null,
  "created" integer not null,
  "currency" text,
  "currency_options" jsonb not null,
  "duration" text not null,
  "duration_in_months" integer,
  "id" text not null,
  "livemode" boolean not null,
  "max_redemptions" integer,
  "metadata" jsonb,
  "name" text,
  "object" text not null,
  "percent_off" integer,
  "redeem_by" integer,
  "times_redeemed" integer not null,
  "valid" boolean not null
);
CREATE TABLE stripe.credit_note (
  "amount" integer not null,
  "created" integer not null,
  "currency" text not null,
  "customer" jsonb not null,
  "customer_balance_transaction" jsonb not null,
  "discount_amount" integer not null,
  "discount_amounts" jsonb not null,
  "id" text not null,
  "invoice" jsonb not null,
  "lines" jsonb not null,
  "livemode" boolean not null,
  "memo" text,
  "metadata" jsonb,
  "number" text not null,
  "object" text not null,
  "out_of_band_amount" integer,
  "pdf" text not null,
  "reason" text,
  "refund" jsonb not null,
  "status" text not null,
  "subtotal" integer not null,
  "subtotal_excluding_tax" integer,
  "tax_amounts" jsonb not null,
  "total" integer not null,
  "total_excluding_tax" integer,
  "type" text not null,
  "voided_at" integer
);
CREATE TABLE stripe.customer (
  "address" jsonb not null,
  "balance" integer not null,
  "cash_balance" jsonb not null,
  "created" integer not null,
  "currency" text,
  "default_source" jsonb not null,
  "delinquent" boolean,
  "description" text,
  "discount" jsonb not null,
  "email" text,
  "id" text not null,
  "invoice_credit_balance" jsonb not null,
  "invoice_prefix" text,
  "invoice_settings" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "name" text,
  "next_invoice_sequence" integer not null,
  "object" text not null,
  "phone" text,
  "preferred_locales" jsonb,
  "shipping" jsonb not null,
  "sources" jsonb not null,
  "subscriptions" jsonb not null,
  "tax" jsonb not null,
  "tax_exempt" text,
  "tax_ids" jsonb not null,
  "test_clock" jsonb not null
);
CREATE TABLE stripe.discount (
  "checkout_session" text,
  "coupon" jsonb not null,
  "customer" jsonb not null,
  "end" integer,
  "id" text not null,
  "invoice" text,
  "invoice_item" text,
  "object" text not null,
  "promotion_code" jsonb not null,
  "start" integer not null,
  "subscription" text
);
CREATE TABLE stripe.source (
  "ach_credit_transfer" jsonb not null,
  "ach_debit" jsonb not null,
  "acss_debit" jsonb not null,
  "alipay" jsonb not null,
  "amount" integer,
  "au_becs_debit" jsonb not null,
  "bancontact" jsonb not null,
  "card" jsonb not null,
  "card_present" jsonb not null,
  "client_secret" text not null,
  "code_verification" jsonb not null,
  "created" integer not null,
  "currency" text,
  "customer" text not null,
  "eps" jsonb not null,
  "flow" text not null,
  "giropay" jsonb not null,
  "id" text not null,
  "ideal" jsonb not null,
  "klarna" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "multibanco" jsonb not null,
  "object" text not null,
  "owner" jsonb not null,
  "p24" jsonb not null,
  "receiver" jsonb not null,
  "redirect" jsonb not null,
  "sepa_debit" jsonb not null,
  "sofort" jsonb not null,
  "source_order" jsonb not null,
  "statement_descriptor" text,
  "status" text not null,
  "three_d_secure" jsonb not null,
  "type" text not null,
  "usage" text,
  "wechat" jsonb not null
);
CREATE TABLE stripe.subscription (
  "application" jsonb not null,
  "application_fee_percent" integer,
  "automatic_tax" jsonb not null,
  "billing_cycle_anchor" integer not null,
  "billing_thresholds" jsonb not null,
  "cancel_at" integer,
  "cancel_at_period_end" boolean not null,
  "canceled_at" integer,
  "collection_method" text not null,
  "created" integer not null,
  "currency" text not null,
  "current_period_end" integer not null,
  "current_period_start" integer not null,
  "customer" jsonb not null,
  "days_until_due" integer,
  "default_payment_method" jsonb not null,
  "default_source" jsonb not null,
  "default_tax_rates" jsonb,
  "description" text,
  "discount" jsonb not null,
  "ended_at" integer,
  "id" text not null,
  "items" jsonb not null,
  "latest_invoice" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "next_pending_invoice_item_invoice" integer,
  "object" text not null,
  "pause_collection" jsonb not null,
  "payment_settings" jsonb not null,
  "pending_invoice_item_interval" jsonb not null,
  "pending_setup_intent" jsonb not null,
  "pending_update" jsonb not null,
  "schedule" jsonb not null,
  "start_date" integer not null,
  "status" text not null,
  "test_clock" jsonb not null,
  "transfer_data" jsonb not null,
  "trial_end" integer,
  "trial_start" integer
);
CREATE TABLE stripe.tax_id (
  "country" text,
  "created" integer not null,
  "customer" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "type" text not null,
  "value" text not null,
  "verification" jsonb not null
);
CREATE TABLE stripe.file (
  "created" integer not null,
  "expires_at" integer,
  "filename" text,
  "id" text not null,
  "links" jsonb,
  "object" text not null,
  "purpose" text not null,
  "size" integer not null,
  "title" text,
  "type" text,
  "url" text
);
CREATE TABLE stripe.verification_session (
  "client_secret" text,
  "created" integer not null,
  "id" text not null,
  "last_error" jsonb not null,
  "last_verification_report" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "options" jsonb not null,
  "redaction" jsonb not null,
  "status" text not null,
  "type" text not null,
  "url" text,
  "verified_outputs" jsonb not null
);
CREATE TABLE stripe.invoice (
  "account_country" text,
  "account_name" text,
  "account_tax_ids" jsonb,
  "amount_due" integer not null,
  "amount_paid" integer not null,
  "amount_remaining" integer not null,
  "application" jsonb not null,
  "application_fee_amount" integer,
  "attempt_count" integer not null,
  "attempted" boolean not null,
  "auto_advance" boolean not null,
  "automatic_tax" jsonb not null,
  "billing_reason" text,
  "charge" jsonb not null,
  "collection_method" text not null,
  "created" integer not null,
  "currency" text not null,
  "custom_fields" jsonb,
  "customer" jsonb not null,
  "customer_address" jsonb not null,
  "customer_email" text,
  "customer_name" text,
  "customer_phone" text,
  "customer_shipping" jsonb not null,
  "customer_tax_exempt" text,
  "customer_tax_ids" jsonb,
  "default_payment_method" jsonb not null,
  "default_source" jsonb not null,
  "default_tax_rates" jsonb not null,
  "description" text,
  "discount" jsonb not null,
  "discounts" jsonb,
  "due_date" integer,
  "ending_balance" integer,
  "footer" text,
  "hosted_invoice_url" text,
  "id" text not null,
  "invoice_pdf" text,
  "last_finalization_error" jsonb not null,
  "lines" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "next_payment_attempt" integer,
  "number" text,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "paid" boolean not null,
  "paid_out_of_band" boolean not null,
  "payment_intent" jsonb not null,
  "payment_settings" jsonb not null,
  "period_end" integer not null,
  "period_start" integer not null,
  "post_payment_credit_notes_amount" integer not null,
  "pre_payment_credit_notes_amount" integer not null,
  "quote" jsonb not null,
  "receipt_number" text,
  "rendering_options" jsonb not null,
  "starting_balance" integer not null,
  "statement_descriptor" text,
  "status" text,
  "status_transitions" jsonb not null,
  "subscription" jsonb not null,
  "subscription_proration_date" integer not null,
  "subtotal" integer not null,
  "subtotal_excluding_tax" integer,
  "tax" integer,
  "test_clock" jsonb not null,
  "threshold_reason" jsonb not null,
  "total" integer not null,
  "total_discount_amounts" jsonb,
  "total_excluding_tax" integer,
  "total_tax_amounts" jsonb not null,
  "transfer_data" jsonb not null,
  "webhooks_delivered_at" integer
);
CREATE TABLE stripe.invoiceitem (
  "amount" integer not null,
  "currency" text not null,
  "customer" jsonb not null,
  "date" integer not null,
  "description" text,
  "discountable" boolean not null,
  "discounts" jsonb,
  "id" text not null,
  "invoice" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "period" jsonb not null,
  "price" jsonb not null,
  "proration" boolean not null,
  "quantity" integer not null,
  "subscription" jsonb not null,
  "subscription_item" text not null,
  "tax_rates" jsonb,
  "test_clock" jsonb not null,
  "unit_amount" integer,
  "unit_amount_decimal" text
);
CREATE TABLE stripe.issuing_authorization (
  "amount" integer not null,
  "amount_details" jsonb not null,
  "approved" boolean not null,
  "authorization_method" text not null,
  "balance_transactions" jsonb not null,
  "card" jsonb not null,
  "cardholder" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "id" text not null,
  "livemode" boolean not null,
  "merchant_amount" integer not null,
  "merchant_currency" text not null,
  "merchant_data" jsonb not null,
  "metadata" jsonb not null,
  "object" text not null,
  "pending_request" jsonb not null,
  "request_history" jsonb not null,
  "status" text not null,
  "transactions" jsonb not null,
  "treasury" jsonb not null,
  "verification_data" jsonb not null,
  "wallet" text
);
CREATE TABLE stripe.issuing_card (
  "brand" text not null,
  "cancellation_reason" text,
  "cardholder" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "cvc" text not null,
  "exp_month" integer not null,
  "exp_year" integer not null,
  "financial_account" text,
  "id" text not null,
  "last4" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "number" text not null,
  "object" text not null,
  "replaced_by" jsonb not null,
  "replacement_for" jsonb not null,
  "replacement_reason" text,
  "shipping" jsonb not null,
  "spending_controls" jsonb not null,
  "status" text not null,
  "type" text not null,
  "wallets" jsonb not null
);
CREATE TABLE stripe.issuing_cardholder (
  "billing" jsonb not null,
  "company" jsonb not null,
  "created" integer not null,
  "email" text,
  "id" text not null,
  "individual" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "name" text not null,
  "object" text not null,
  "phone_number" text,
  "requirements" jsonb not null,
  "spending_controls" jsonb not null,
  "status" text not null,
  "type" text not null
);
CREATE TABLE stripe.issuing_dispute (
  "amount" integer not null,
  "balance_transactions" jsonb,
  "created" integer not null,
  "currency" text not null,
  "evidence" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "status" text not null,
  "transaction" jsonb not null,
  "treasury" jsonb not null
);
CREATE TABLE stripe.issuing_transaction (
  "amount" integer not null,
  "amount_details" jsonb not null,
  "authorization" jsonb not null,
  "balance_transaction" jsonb not null,
  "card" jsonb not null,
  "cardholder" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "dispute" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "merchant_amount" integer not null,
  "merchant_currency" text not null,
  "merchant_data" jsonb not null,
  "metadata" jsonb not null,
  "object" text not null,
  "purchase_details" jsonb not null,
  "treasury" jsonb not null,
  "type" text not null,
  "wallet" text
);
CREATE TABLE stripe.mandate (
  "customer_acceptance" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "multi_use" jsonb not null,
  "object" text not null,
  "payment_method" jsonb not null,
  "payment_method_details" jsonb not null,
  "single_use" jsonb not null,
  "status" text not null,
  "type" text not null
);
CREATE TABLE stripe.order (
  "amount_subtotal" integer not null,
  "amount_total" integer not null,
  "application" jsonb not null,
  "automatic_tax" jsonb not null,
  "billing_details" jsonb not null,
  "client_secret" text,
  "created" integer not null,
  "currency" text not null,
  "customer" jsonb not null,
  "description" text,
  "discounts" jsonb,
  "id" text not null,
  "ip_address" text,
  "line_items" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "payment" jsonb not null,
  "shipping_cost" jsonb not null,
  "shipping_details" jsonb not null,
  "status" text not null,
  "tax_details" jsonb not null,
  "total_details" jsonb not null
);
CREATE TABLE stripe.payment_intent (
  "amount" integer not null,
  "amount_capturable" integer not null,
  "amount_details" jsonb not null,
  "amount_received" integer not null,
  "application" jsonb not null,
  "application_fee_amount" integer,
  "automatic_payment_methods" jsonb not null,
  "canceled_at" integer,
  "cancellation_reason" text,
  "capture_method" text not null,
  "charges" jsonb not null,
  "client_secret" text,
  "confirmation_method" text not null,
  "created" integer not null,
  "currency" text not null,
  "customer" jsonb not null,
  "description" text,
  "id" text not null,
  "invoice" jsonb not null,
  "last_payment_error" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "next_action" jsonb not null,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "payment_method" jsonb not null,
  "payment_method_options" jsonb not null,
  "payment_method_types" jsonb not null,
  "processing" jsonb not null,
  "receipt_email" text,
  "review" jsonb not null,
  "setup_future_usage" text,
  "shipping" jsonb not null,
  "statement_descriptor" text,
  "statement_descriptor_suffix" text,
  "status" text not null,
  "transfer_data" jsonb not null,
  "transfer_group" text
);
CREATE TABLE stripe.payment_link (
  "active" boolean not null,
  "after_completion" jsonb not null,
  "allow_promotion_codes" boolean not null,
  "application_fee_amount" integer,
  "application_fee_percent" integer,
  "automatic_tax" jsonb not null,
  "billing_address_collection" text not null,
  "consent_collection" jsonb not null,
  "currency" text not null,
  "customer_creation" text not null,
  "id" text not null,
  "line_items" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "payment_intent_data" jsonb not null,
  "payment_method_collection" text not null,
  "payment_method_types" jsonb,
  "phone_number_collection" jsonb not null,
  "shipping_address_collection" jsonb not null,
  "shipping_options" jsonb not null,
  "submit_type" text not null,
  "subscription_data" jsonb not null,
  "tax_id_collection" jsonb not null,
  "transfer_data" jsonb not null,
  "url" text not null
);
CREATE TABLE stripe.payment_method (
  "acss_debit" jsonb not null,
  "affirm" jsonb not null,
  "afterpay_clearpay" jsonb not null,
  "alipay" jsonb not null,
  "au_becs_debit" jsonb not null,
  "bacs_debit" jsonb not null,
  "bancontact" jsonb not null,
  "billing_details" jsonb not null,
  "blik" jsonb not null,
  "boleto" jsonb not null,
  "card" jsonb not null,
  "card_present" jsonb not null,
  "created" integer not null,
  "customer" jsonb not null,
  "customer_balance" jsonb not null,
  "eps" jsonb not null,
  "fpx" jsonb not null,
  "giropay" jsonb not null,
  "grabpay" jsonb not null,
  "id" text not null,
  "ideal" jsonb not null,
  "interac_present" jsonb not null,
  "klarna" jsonb not null,
  "konbini" jsonb not null,
  "link" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "oxxo" jsonb not null,
  "p24" jsonb not null,
  "paynow" jsonb not null,
  "promptpay" jsonb not null,
  "radar_options" jsonb not null,
  "sepa_debit" jsonb not null,
  "sofort" jsonb not null,
  "type" text not null,
  "us_bank_account" jsonb not null,
  "wechat_pay" jsonb not null
);
CREATE TABLE stripe.payout (
  "amount" integer not null,
  "arrival_date" integer not null,
  "automatic" boolean not null,
  "balance_transaction" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "description" text,
  "destination" jsonb not null,
  "failure_balance_transaction" jsonb not null,
  "failure_code" text,
  "failure_message" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "method" text not null,
  "object" text not null,
  "original_payout" jsonb not null,
  "reversed_by" jsonb not null,
  "source_type" text not null,
  "statement_descriptor" text,
  "status" text not null,
  "type" text not null
);
CREATE TABLE stripe.person (
  "account" text not null,
  "address" jsonb not null,
  "address_kana" jsonb not null,
  "address_kanji" jsonb not null,
  "created" integer not null,
  "dob" jsonb not null,
  "email" text,
  "first_name" text,
  "first_name_kana" text,
  "first_name_kanji" text,
  "full_name_aliases" jsonb not null,
  "future_requirements" jsonb not null,
  "gender" text,
  "id" text not null,
  "id_number_provided" boolean not null,
  "id_number_secondary_provided" boolean not null,
  "last_name" text,
  "last_name_kana" text,
  "last_name_kanji" text,
  "maiden_name" text,
  "metadata" jsonb not null,
  "nationality" text,
  "object" text not null,
  "phone" text,
  "political_exposure" text not null,
  "registered_address" jsonb not null,
  "relationship" jsonb not null,
  "requirements" jsonb not null,
  "ssn_last_4_provided" boolean not null,
  "verification" jsonb not null
);
CREATE TABLE stripe.plan (
  "active" boolean not null,
  "aggregate_usage" text,
  "amount" integer,
  "amount_decimal" text,
  "billing_scheme" text not null,
  "created" integer not null,
  "currency" text not null,
  "id" text not null,
  "interval" text not null,
  "interval_count" integer not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "nickname" text,
  "object" text not null,
  "product" jsonb not null,
  "tiers" jsonb not null,
  "tiers_mode" text,
  "transform_usage" jsonb not null,
  "trial_period_days" integer,
  "usage_type" text not null
);
CREATE TABLE stripe.price (
  "active" boolean not null,
  "billing_scheme" text not null,
  "created" integer not null,
  "currency" text not null,
  "currency_options" jsonb not null,
  "custom_unit_amount" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "lookup_key" text,
  "metadata" jsonb not null,
  "nickname" text,
  "object" text not null,
  "product" jsonb not null,
  "recurring" jsonb not null,
  "tax_behavior" text,
  "tiers" jsonb not null,
  "tiers_mode" text,
  "transform_quantity" jsonb not null,
  "type" text not null,
  "unit_amount" integer,
  "unit_amount_decimal" text
);
CREATE TABLE stripe.product (
  "active" boolean not null,
  "created" integer not null,
  "default_price" jsonb not null,
  "description" text,
  "id" text not null,
  "images" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "name" text not null,
  "object" text not null,
  "package_dimensions" jsonb not null,
  "shippable" boolean,
  "statement_descriptor" text,
  "tax_code" jsonb not null,
  "unit_label" text,
  "updated" integer not null,
  "url" text
);
CREATE TABLE stripe.promotion_code (
  "active" boolean not null,
  "code" text not null,
  "coupon" jsonb not null,
  "created" integer not null,
  "customer" jsonb not null,
  "expires_at" integer,
  "id" text not null,
  "livemode" boolean not null,
  "max_redemptions" integer,
  "metadata" jsonb,
  "object" text not null,
  "restrictions" jsonb not null,
  "times_redeemed" integer not null
);
CREATE TABLE stripe.quote (
  "amount_subtotal" integer not null,
  "amount_total" integer not null,
  "application" jsonb not null,
  "application_fee_amount" integer,
  "application_fee_percent" integer,
  "automatic_tax" jsonb not null,
  "collection_method" text not null,
  "computed" jsonb not null,
  "created" integer not null,
  "currency" text,
  "customer" jsonb not null,
  "default_tax_rates" jsonb not null,
  "description" text,
  "discounts" jsonb not null,
  "expires_at" integer not null,
  "footer" text,
  "from_quote" jsonb not null,
  "header" text,
  "id" text not null,
  "invoice" jsonb not null,
  "invoice_settings" jsonb not null,
  "line_items" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "number" text,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "subscription" jsonb not null,
  "subscription_data" jsonb not null,
  "subscription_schedule" jsonb not null,
  "test_clock" jsonb not null,
  "total_details" jsonb not null,
  "transfer_data" jsonb not null
);
CREATE TABLE stripe.early_fraud_warning (
  "actionable" boolean not null,
  "charge" jsonb not null,
  "created" integer not null,
  "fraud_type" text not null,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "payment_intent" jsonb not null
);
CREATE TABLE stripe.recipient (
  "active_account" jsonb not null,
  "cards" jsonb,
  "created" integer not null,
  "default_card" jsonb not null,
  "description" text,
  "email" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "migrated_to" jsonb not null,
  "name" text,
  "object" text not null,
  "rolled_back_from" jsonb not null,
  "type" text not null
);
CREATE TABLE stripe.report_run (
  "created" integer not null,
  "error" text,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "parameters" jsonb not null,
  "report_type" text not null,
  "result" jsonb not null,
  "status" text not null,
  "succeeded_at" integer
);
CREATE TABLE stripe.report_type (
  "data_available_end" integer not null,
  "data_available_start" integer not null,
  "default_columns" jsonb,
  "id" text not null,
  "livemode" boolean not null,
  "name" text not null,
  "object" text not null,
  "updated" integer not null,
  "version" integer not null
);
CREATE TABLE stripe.review (
  "billing_zip" text,
  "charge" jsonb not null,
  "closed_reason" text,
  "created" integer not null,
  "id" text not null,
  "ip_address" text,
  "ip_address_location" jsonb not null,
  "livemode" boolean not null,
  "object" text not null,
  "open" boolean not null,
  "opened_reason" text not null,
  "payment_intent" jsonb not null,
  "reason" text not null,
  "session" jsonb not null
);
CREATE TABLE stripe.setup_intent (
  "application" jsonb not null,
  "attach_to_self" boolean not null,
  "cancellation_reason" text,
  "client_secret" text,
  "created" integer not null,
  "customer" jsonb not null,
  "description" text,
  "flow_directions" jsonb,
  "id" text not null,
  "last_setup_error" jsonb not null,
  "latest_attempt" jsonb not null,
  "livemode" boolean not null,
  "mandate" jsonb not null,
  "metadata" jsonb,
  "next_action" jsonb not null,
  "object" text not null,
  "on_behalf_of" jsonb not null,
  "payment_method" jsonb not null,
  "payment_method_options" jsonb not null,
  "payment_method_types" jsonb not null,
  "single_use_mandate" jsonb not null,
  "status" text not null,
  "usage" text not null
);
CREATE TABLE stripe.scheduled_query_run (
  "created" integer not null,
  "data_load_time" integer not null,
  "error" jsonb not null,
  "file" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "result_available_until" integer not null,
  "sql" text not null,
  "status" text not null,
  "title" text not null
);
CREATE TABLE stripe.sku (
  "active" boolean not null,
  "attributes" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "id" text not null,
  "image" text,
  "inventory" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "package_dimensions" jsonb not null,
  "price" integer not null,
  "product" jsonb not null,
  "updated" integer not null
);
CREATE TABLE stripe.transaction (
  "ach_credit_transfer" jsonb not null,
  "amount" integer not null,
  "chf_credit_transfer" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "gbp_credit_transfer" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "object" text not null,
  "paper_check" jsonb not null,
  "sepa_credit_transfer" jsonb not null,
  "source" text not null,
  "status" text not null,
  "type" text not null
);
CREATE TABLE stripe.subscription_schedule (
  "application" jsonb not null,
  "canceled_at" integer,
  "completed_at" integer,
  "created" integer not null,
  "current_phase" jsonb not null,
  "customer" jsonb not null,
  "default_settings" jsonb not null,
  "end_behavior" text not null,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "phases" jsonb not null,
  "released_at" integer,
  "released_subscription" text,
  "status" text not null,
  "subscription" jsonb not null,
  "test_clock" jsonb not null
);
CREATE TABLE stripe.tax_rate (
  "active" boolean not null,
  "country" text,
  "created" integer not null,
  "description" text,
  "display_name" text not null,
  "id" text not null,
  "inclusive" boolean not null,
  "jurisdiction" text,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "percentage" integer not null,
  "state" text,
  "tax_type" text
);
CREATE TABLE stripe.reader (
  "action" jsonb not null,
  "device_sw_version" text,
  "device_type" text not null,
  "id" text not null,
  "ip_address" text,
  "label" text not null,
  "livemode" boolean not null,
  "location" jsonb not null,
  "metadata" jsonb not null,
  "object" text not null,
  "serial_number" text not null,
  "status" text
);
CREATE TABLE stripe.test_clock (
  "created" integer not null,
  "deletes_after" integer not null,
  "frozen_time" integer not null,
  "id" text not null,
  "livemode" boolean not null,
  "name" text,
  "object" text not null,
  "status" text not null
);
CREATE TABLE stripe.topup (
  "amount" integer not null,
  "balance_transaction" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "description" text,
  "expected_availability_date" integer,
  "failure_code" text,
  "failure_message" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "source" jsonb not null,
  "statement_descriptor" text,
  "status" text not null,
  "transfer_group" text
);
CREATE TABLE stripe.transfer (
  "amount" integer not null,
  "amount_reversed" integer not null,
  "balance_transaction" jsonb not null,
  "created" integer not null,
  "currency" text not null,
  "description" text,
  "destination" jsonb not null,
  "destination_payment" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "reversals" jsonb not null,
  "reversed" boolean not null,
  "source_transaction" jsonb not null,
  "source_type" text not null,
  "transfer_group" text
);
CREATE TABLE stripe.credit_reversal (
  "amount" integer not null,
  "currency" text not null,
  "financial_account" text not null,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "network" text not null,
  "object" text not null,
  "received_credit" text not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.debit_reversal (
  "amount" integer not null,
  "currency" text not null,
  "financial_account" text,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "linked_flows" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "network" text not null,
  "object" text not null,
  "received_debit" text not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.financial_account (
  "active_features" jsonb not null,
  "balance" jsonb not null,
  "country" text not null,
  "created" integer not null,
  "features" jsonb not null,
  "financial_addresses" jsonb not null,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb,
  "object" text not null,
  "pending_features" jsonb not null,
  "platform_restrictions" jsonb not null,
  "restricted_features" jsonb not null,
  "status" text not null,
  "status_details" jsonb not null,
  "supported_currencies" jsonb not null
);
CREATE TABLE stripe.inbound_transfer (
  "amount" integer not null,
  "cancelable" boolean not null,
  "created" integer not null,
  "currency" text not null,
  "description" text,
  "failure_details" jsonb not null,
  "financial_account" text not null,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "linked_flows" jsonb not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "origin_payment_method" text not null,
  "origin_payment_method_details" jsonb not null,
  "returned" boolean,
  "statement_descriptor" text not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.outbound_payment (
  "amount" integer not null,
  "cancelable" boolean not null,
  "created" integer not null,
  "currency" text not null,
  "customer" text,
  "description" text,
  "destination_payment_method" text,
  "destination_payment_method_details" jsonb not null,
  "end_user_details" jsonb not null,
  "expected_arrival_date" integer not null,
  "financial_account" text not null,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "returned_details" jsonb not null,
  "statement_descriptor" text not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.outbound_transfer (
  "amount" integer not null,
  "cancelable" boolean not null,
  "created" integer not null,
  "currency" text not null,
  "description" text,
  "destination_payment_method" text not null,
  "destination_payment_method_details" jsonb not null,
  "expected_arrival_date" integer not null,
  "financial_account" text not null,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "livemode" boolean not null,
  "metadata" jsonb not null,
  "object" text not null,
  "returned_details" jsonb not null,
  "statement_descriptor" text not null,
  "status" text not null,
  "status_transitions" jsonb not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.received_credit (
  "amount" integer not null,
  "created" integer not null,
  "currency" text not null,
  "description" text not null,
  "failure_code" text,
  "financial_account" text,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "initiating_payment_method_details" jsonb not null,
  "linked_flows" jsonb not null,
  "livemode" boolean not null,
  "network" text not null,
  "object" text not null,
  "reversal_details" jsonb not null,
  "status" text not null,
  "transaction" jsonb not null
);
CREATE TABLE stripe.received_debit (
  "amount" integer not null,
  "created" integer not null,
  "currency" text not null,
  "description" text not null,
  "failure_code" text,
  "financial_account" text,
  "hosted_regulatory_receipt_url" text,
  "id" text not null,
  "initiating_payment_method_details" jsonb not null,
  "linked_flows" jsonb not null,
  "livemode" boolean not null,
  "network" text not null,
  "object" text not null,
  "reversal_details" jsonb not null,
  "status" text not null,
  "transaction" jsonb not null
);
